## 파일 입출력

In [ ]:
import os
os.getwd()

In [8]:
import pandas as pd

sample_df = pd.DataFrame({"col1" : [1, 2], "col2" : [3, 4]})
sample_df.to_csv('output/sample/sample_df.csv',index = False)    # 파일명 test.csv index=False

In [10]:
df = pd.read_csv('output/sample/sample_df.csv')

TypeError: read_csv() got an unexpected keyword argument 'index'

In [17]:
df_boston = pd.read_csv('./data/boston.csv')
df_boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

## 열 및 행 선택
- CRIM, ZN, INDUS 열을 선택함

In [22]:
cols = ['CRIM', 'ZN', 'INDUS']
result = df_boston[cols]
print(result)

        CRIM    ZN  INDUS
0    0.00632  18.0   2.31
1    0.02731   0.0   7.07
2    0.02729   0.0   7.07
3    0.03237   0.0   2.18
4    0.06905   0.0   2.18
..       ...   ...    ...
501  0.06263   0.0  11.93
502  0.04527   0.0  11.93
503  0.06076   0.0  11.93
504  0.10959   0.0  11.93
505  0.04741   0.0  11.93

[506 rows x 3 columns]


- ZN이 18.0에 해당하는 행만 추출

In [26]:
# 행 추출의 기본원리는 조건문
result = df_boston[df_boston['ZN'] == 18.0]
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  target  
0  396.9   4.98    24.0

- AGE가 50이상인 데이만 추출

In [28]:
result = df_boston[df_boston['AGE'] >= 50].
result

True

In [39]:
result = df_boston[(df_boston['INDUS'] >= 5.0) & (df_boston['B'] >= 394) & (df_boston['target'] >= 22)]
# result = df_boston[(df_boston['INDUS'] > 5.0) & (df_boston['B'] >= 394)]
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
6    0.08829  12.5   7.87   0.0  0.524  6.012  66.6  5.5605   5.0  311.0   
7    0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505   5.0  311.0   
43   0.15936   0.0   6.91   0.0  0.448  6.211   6.5  5.7209   3.0  233.0   
52   0.05360  21.0   5.64   0.0  0.439  6.511  21.1  6.8147   4.0  243.0   
53   0.04981  21.0   5.64   0.0  0.439  5.998  21.4  6.8147   4.0  243.0   
62   0.11027  25.0   5.13   0.0  0.453  6.456  67.8  7.2255   8.0  284.0   
63   0.12650  25.0   5.13   0.0  0.453  6.762  43.4  7.9809   8.0  284.0   
67   0.05789  12.5   6.07   0.0  0.409  5.878  21.4  6.4980   4.0  345.0   
74   0.07896   0.0  12.83   0.0  0.437  6.273   6.0  4.2515   5.0  398.0   
92   0.04203  28.0  15.04   0.0  0.464  6.442  53.6  3.6659   4.0  270.0   
93   0.02875  28.0  15.04   0.0  0.464  6.211  28.9  3.6659   4.0  270.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778   5.0  384.0   
101  0.11432   0.0   8.56   0.0  0.520  6.781  71.3  2.8561   5.0  384.0   
111  0.10084   0.0  10.01   0.0  0.547  6.715  81.6  2.6775   6.0  432.0   
164  2.24236   0.0  19.58   0.0  0.605  5.854  91.8  2.4220   5.0  403.0   
205  0.13642   0.0  10.59   0.0  0.489  5.891  22.3  3.9454   4.0  277.0   
206  0.22969   0.0  10.59   0.0  0.489  6.326  52.5  4.3549   4.0  277.0   
223  0.61470   0.0   6.20   0.0  0.507  6.618  80.8  3.2721   8.0  307.0   
250  0.14030  22.0   5.86   0.0  0.431  6.487  13.0  7.3967   7.0  330.0   
253  0.36894  22.0   5.86   0.0  0.431  8.259   8.4  8.9067   7.0  330.0   
271  0.16211  20.0   6.96   0.0  0.464  6.240  16.3  4.4290   3.0  223.0   
272  0.11460  20.0   6.96   0.0  0.464  6.538  58.7  3.9175   3.0  223.0   
274  0.05644  40.0   6.41   1.0  0.447  6.758  32.9  4.0776   4.0  254.0   
275  0.09604  40.0   6.41   0.0  0.447  6.854  42.8  4.2673   4.0  254.0   
278  0.07978  40.0   6.41   0.0  0.447  6.482  32.1  4.1403   4.0  254.0   
287  0.03871  52.5   5.32   0.0  0.405  6.209  31.3  7.3172   6.0  293.0   
288  0.04590  52.5   5.32   0.0  0.405  6.315  45.6  7.3172   6.0  293.0   
293  0.08265   0.0  13.92   0.0  0.437  6.127  18.4  5.5027   4.0  289.0   
295  0.12932   0.0  13.92   0.0  0.437  6.678  31.1  5.9604   4.0  289.0   
301  0.03537  34.0   6.09   0.0  0.433  6.590  40.4  5.4917   7.0  329.0   
308  0.49298   0.0   9.90   0.0  0.544  6.635  82.5  3.3175   4.0  304.0   
311  0.79041   0.0   9.90   0.0  0.544  6.122  52.8  2.6403   4.0  304.0   
314  0.36920   0.0   9.90   0.0  0.544  6.567  87.3  3.6023   4.0  304.0   
318  0.40202   0.0   9.90   0.0  0.544  6.382  67.2  3.5325   4.0  304.0   
320  0.16760   0.0   7.38   0.0  0.493  6.426  52.3  4.5404   5.0  287.0   
321  0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
324  0.34109   0.0   7.38   0.0  0.493  6.415  40.1  4.7211   5.0  287.0   
326  0.30347   0.0   7.38   0.0  0.493  6.312  28.9  5.4159   5.0  287.0   
327  0.24103   0.0   7.38   0.0  0.493  6.083  43.7  5.4159   5.0  287.0   
358  5.20177   0.0  18.10   1.0  0.770  6.127  83.4  2.7227  24.0  666.0   
480  5.82401   0.0  18.10   0.0  0.532  6.242  64.7  3.4242  24.0  666.0   
482  5.73116   0.0  18.10   0.0  0.532  7.061  77.0  3.4106  24.0  666.0   
494  0.27957   0.0   9.69   0.0  0.585  5.926  42.6  2.3817   6.0  391.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675   1.0  273.0   

     PTRATIO       B  LSTAT  target  
6       15.2  395.60  12.43    22.9  
7       15.2  396.90  19.15    27.1  
43      17.9  394.46   7.44    24.7  
52      16.8  396.90   5.28    25.0  
53      16.8  396.90   8.43    23.4  
62      19.7  396.90   6.73    22.2  
63      19.7  395.58   9.50    25.0  
67      18.9  396.21   8.10    22.0  
74      18.7  394.92   6.78    24.1  
92      18.2  395.01   8.16    22.9  
93      18.2  396.33   6.21    25.0  
100     20.9  394.76   9.42    27.5  
101     20.9  395.58   7.67    26.5  
111     17.8  395.59  10.16    22.8  
164     14.7  395

In [40]:
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [55]:
# iloc 활용해서 추출
df_boston.iloc[:3,:3]

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07

In [54]:
# loc 활용해서 추출
df_boston.loc[:2, :'INDUS']

CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07
2  0.02729   0.0   7.07

In [60]:
result = df_boston.loc[df_boston['INDUS']>=5.0, ["CRIM", "ZN", "INDUS"]].reset_index(drop=True)    # loc만 쓰
result

CRIM    ZN  INDUS
0    0.02731   0.0   7.07
1    0.02729   0.0   7.07
2    0.08829  12.5   7.87
3    0.14455  12.5   7.87
4    0.21124  12.5   7.87
..       ...   ...    ...
381  0.06263   0.0  11.93
382  0.04527   0.0  11.93
383  0.06076   0.0  11.93
384  0.10959   0.0  11.93
385  0.04741   0.0  11.93

[386 rows x 3 columns]

In [64]:
result = df_boston.loc[(df_boston['INDUS']>=5.0) & (df_boston['B']>=394)    # 행
                        , ["CRIM", "ZN", "INDUS"]].reset_index(drop=True)    # 열 

result

CRIM    ZN  INDUS
0    0.02731   0.0   7.07
1    0.08829  12.5   7.87
2    0.14455  12.5   7.87
3    0.11747  12.5   7.87
4    0.62976   0.0   8.14
..       ...   ...    ...
138  0.17783   0.0   9.69
139  0.22438   0.0   9.69
140  0.04527   0.0  11.93
141  0.06076   0.0  11.93
142  0.04741   0.0  11.93

[143 rows x 3 columns]

## 결측치 다루기

In [68]:
import pandas as pd
import numpy as np

np.random.seed(0)    # 초전도체 현상, 실험 조건
data = np.random.randint(0, 10, size=(10, 3)).astype(float)
print(data)

[[5. 0. 3.]
 [3. 7. 9.]
 [3. 5. 2.]
 [4. 7. 6.]
 [8. 8. 1.]
 [6. 7. 7.]
 [8. 1. 5.]
 [9. 8. 9.]
 [4. 3. 0.]
 [3. 5. 0.]]


In [69]:
data[data < 3] = np.nan
print(data)

[[ 5. nan  3.]
 [ 3.  7.  9.]
 [ 3.  5. nan]
 [ 4.  7.  6.]
 [ 8.  8. nan]
 [ 6.  7.  7.]
 [ 8. nan  5.]
 [ 9.  8.  9.]
 [ 4.  3. nan]
 [ 3.  5. nan]]


In [71]:
df = pd.DataFrame(data,columns=['col1', 'col2', 'col3'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     float64
 1   col2    8 non-null      float64
 2   col3    6 non-null      float64
dtypes: float64(3)
memory usage: 372.0 bytes


In [72]:
df.isna().sum()

col1    0
col2    2
col3    4
dtype: int64

In [82]:
# 평균으로 대치 해보기
col3_mean = df['col3'].mean()

df['col3'] = df['col3'].fillna(col3_mean)
df['col2'] = df['col2'].fillna(df['col2'].mean())
df

col1  col2  col3
0   5.0  6.25   3.0
1   3.0  7.00   9.0
2   3.0  5.00   6.5
3   4.0  7.00   6.0
4   8.0  8.00   6.5
5   6.0  7.00   7.0
6   8.0  6.25   5.0
7   9.0  8.00   9.0
8   4.0  3.00   6.5
9   3.0  5.00   6.5

## 행추가

In [86]:
df = pd.DataFrame({
    "이름": ["Evan", "Sara", "Chris", "Messi", "Woods", "Jordan"], 
    "국어": [70, 90, None, None, 100, 85], 
    "영어": [65, 100, None, 90, 70, 80]
})
df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0

In [87]:
df.loc[6, "이름":"영어"] = ["Kim", 50, 60]
df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0
6     Kim   50.0   60.0

In [98]:
# 국어점수가 90점 이상이면 "A"
# 국어점수가 80~89점 "B"
# 국어점수가 70~79점 "C"
# 나머지는 F
'''
df.fillna(0, inplace = True)

def get_grade(score):
    if df['국어'] >= 90:
        df['등급'] = 'A'
    elif df['국어'] >= 80:
        df['등급'] = 'B'
    elif df['국어'] >= 70:
        df['등급'] = 'C'
    else:
        df['등급'] = 'F'

df['등급'] = df['국어'].apply(lambda x : get_grade(x))

df
'''

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

- numpy.where, 조건식 한 번만 적용 <br>
if 조건식, 참일 때, 거짓일 때

In [ ]:
# np.where(조건식, 참, np.where(조건식, 참, (np.where(조건식, 참))))
# np.select(다중조건식, 다중결괏값, default ==> else 조건)

In [102]:
condition_list = [(df['국어'] >= 90), (df['국어'] >= 80) & (df['국어'] < 90), (df['국어'] >= 70) & (df['국어'] < 80)]
choice_list = ['A', 'B', 'C']
df['점수'] = np.select(condition_list, choice_list, default = 'F')
df

이름     국어     영어 점수
0    Evan   70.0   65.0  C
1    Sara   90.0  100.0  A
2   Chris    0.0    0.0  F
3   Messi    0.0   90.0  F
4   Woods  100.0   70.0  A
5  Jordan   85.0   80.0  B
6     Kim   50.0   60.0  F

## 날짜 데이터 핸들링

In [109]:
date_string = "2023-03-02"
type(date_string)

datetime_obj = pd.to_datetime(date_string)
print(datetime_obj)
print(type(datetime_obj))

2023-03-02 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>


In [114]:
date_list = ["2023-03-02"]
print(type(date_list))

datetime_obj = pd.to_datetime(date_list)
print(datetime_obj)
print(type(datetime_obj))

<class 'list'>
DatetimeIndex(['2023-03-02'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


## 데이터 가져오기
- raw_sales.csv 파일 가져오기

In [144]:
sales = pd.read_csv('data/raw_sales.csv')
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   datesold      29580 non-null  object
 1   postcode      29580 non-null  int64 
 2   price         29580 non-null  int64 
 3   propertyType  29580 non-null  object
 4   bedrooms      29580 non-null  int64 
dtypes: int64(3), object(2)
memory usage: 1.1+ MB


In [116]:
# 날짜 데이터 변환
sales = pd.to_datetime(sales['datesold'])
sales.info()

<class 'pandas.core.series.Series'>
RangeIndex: 29580 entries, 0 to 29579
Series name: datesold
Non-Null Count  Dtype         
--------------  -----         
29580 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 231.2 KB


In [145]:
sales['datesold'] = pd.to_datetime(sales['datesold'])
sales.info()
print(sales)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB
        datesold  postcode   price propertyType  bedrooms
0     2007-02-07      2607  525000        house         4
1     2007-02-27      2906  290000        house         3
2     2007-03-07      2905  328000        house         3
3     2007-03-09      2905  380000        house         4
4     2007-03-21      2906  310000        house         3
...          ...       ...     ...          ...       ...
29575 2019-07-25      2900  500000         unit         3
29576 201

In [123]:
type(sales['datesold'])

pandas.core.series.Series

In [135]:
# 연도, 월, 일
sales['year'] = sales['datesold'].dt.year
sales['month'] = sales['datesold'].dt.month
sales['day'] = sales['datesold'].dt.day
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


## shift 기능

In [138]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df.head(5)

datesold   price
0 2007-02-07  525000
1 2007-02-27  290000
2 2007-03-07  328000
3 2007-03-09  380000
4 2007-03-21  310000

In [139]:
temp_df['shifted_v1'] = temp_df['price'].shift(1, fill_value=0).astype(int)
temp_df['diff'] = temp_df['price'] - temp_df['shifted_v1']
temp_df

datesold   price  shifted_v1    diff
0     2007-02-07  525000           0  525000
1     2007-02-27  290000      525000 -235000
2     2007-03-07  328000      290000   38000
3     2007-03-09  380000      328000   52000
4     2007-03-21  310000      380000  -70000
...          ...     ...         ...     ...
29575 2019-07-25  500000      475000   25000
29576 2019-07-25  560000      500000   60000
29577 2019-07-26  464950      560000  -95050
29578 2019-07-26  589000      464950  124050
29579 2019-07-26  775000      589000  186000

[29580 rows x 4 columns]

In [140]:
temp_df['shifted_v2'] = temp_df['price'].shift(2, fill_value=0).astype(int)
temp_df['diff2'] = temp_df['price'] - temp_df['shifted_v2']
temp_df.head(5)

datesold   price  shifted_v1    diff  shifted_v2   diff2
0 2007-02-07  525000           0  525000           0  525000
1 2007-02-27  290000      525000 -235000           0  290000
2 2007-03-07  328000      290000   38000      525000 -197000
3 2007-03-09  380000      328000   52000      290000   90000
4 2007-03-21  310000      380000  -70000      328000  -18000

In [142]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()

temp_df['shifted_v3'] = temp_df['price'].shift(-1, fill_value=0).astype(int)
temp_df['shifted_v4'] = temp_df['price'].shift(-2, fill_value=0).astype(int)
temp_df.tail()

datesold   price  shifted_v3  shifted_v4
29575 2019-07-25  500000      560000      464950
29576 2019-07-25  560000      464950      589000
29577 2019-07-26  464950      589000      775000
29578 2019-07-26  589000      775000           0
29579 2019-07-26  775000           0           0

In [146]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB


In [147]:
sales['한글날짜'] = sales['datesold'].dt.strftime('%Y년 %m월 %d일')
sales.head(3)

datesold  postcode   price propertyType  bedrooms           한글날짜
0 2007-02-07      2607  525000        house         4  2007년 02월 07일
1 2007-02-27      2906  290000        house         3  2007년 02월 27일
2 2007-03-07      2905  328000        house         3  2007년 03월 07일

## 결측치 이상치 데이터 핸들링

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import statsmodels
import scipy
import seaborn as sns

print(pd.__version__)
print(np.__version__)
print(matplotlib.__version__)
print(statsmodels.__version__)
print(scipy.__version__)
print(sns.__version__)

2.0.3
1.25.2
3.7.2
0.14.0
1.11.1
0.12.2


In [7]:
DATA_PATH = './'
covidtotals = pd.read_csv(DATA_PATH + "data/covidtotalswithmissings.csv")
covidtotals.head()

iso_code    lastdate     location  \
0      AFG  2020-06-01  Afghanistan   
1      ALB  2020-06-01      Albania   
2      DZA  2020-06-01      Algeria   
3      AND  2020-06-01      Andorra   
4      AGO  2020-06-01       Angola   

   total_cases  total_deaths  \
0        15205           257   
1         1137            33   
2         9394           653   
3          764            51   
4           86             4   

   total_cases_pm  total_deaths_pm  \
0          390.59             6.60   
1          395.09            11.47   
2          214.22            14.89   
3        9,888.05           660.07   
4            2.62             0.12   

     population  pop_density  \
0 38,928,341.00        54.42   
1  2,877,800.00       104.87   
2 43,851,043.00        17.35   
3     77,265.00       163.75   
4 32,866,268.00        23.89   

   median_age  gdp_per_capita  \
0       18.60        1,803.99   
1       38.00       11,803.43   
2       29.10       13,913.84   
3         NaN             NaN   
4       16.80        5,819.49   

   hosp_beds  
0       0.50  
1       2.89  
2       1.90  
3        NaN  
4        NaN

In [8]:
pd.set_option('display.width', 40)
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 20)
pd.options.display.float_format = '{:,.2f}'.format

In [9]:
covidtotals = covidtotals.set_index('iso_code')
covidtotals.head()

lastdate     location  \
iso_code                            
AFG       2020-06-01  Afghanistan   
ALB       2020-06-01      Albania   
DZA       2020-06-01      Algeria   
AND       2020-06-01      Andorra   
AGO       2020-06-01       Angola   

          total_cases  total_deaths  \
iso_code                              
AFG             15205           257   
ALB              1137            33   
DZA              9394           653   
AND               764            51   
AGO                86             4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   
ALB                 11.47   
DZA                 14.89   
AND                660.07   
AGO                  0.12   

            population  pop_density  \
iso_code                              
AFG      38,928,341.00        54.42   
ALB       2,877,800.00       104.87   
DZA      43,851,043.00        17.35   
AND          77,265.00       163.75   
AGO      32,866,268.00        23.89   

          median_age  gdp_per_capita  \
iso_code                               
AFG            18.60        1,803.99   
ALB            38.00       11,803.43   
DZA            29.10       13,913.84   
AND              NaN             NaN   
AGO            16.80        5,819.49   

          hosp_beds  
iso_code             
AFG            0.50  
ALB            2.89  
DZA            1.90  
AND             NaN  
AGO             NaN

# 결측치 처리
- 인구통계 컬럼에서 결측치 데이터를 확인
- 컬럼방향으로 결측치의 갯수를 파악함
- 5가지 인구 통계 변수 중에서 3개가 누락된 곳 확인 

In [10]:
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']
demovars = ['population','pop_density','median_age','gdp_per_capita', 'hosp_beds']

In [11]:
covidtotals[demovars].isnull().sum(axis=0)

population         0
pop_density       12
median_age        24
gdp_per_capita    28
hosp_beds         46
dtype: int64

In [12]:
covidtotals.iloc[3, :]

lastdate           2020-06-01
location              Andorra
total_cases               764
total_deaths               51
total_cases_pm       9,888.05
total_deaths_pm        660.07
population          77,265.00
pop_density            163.75
median_age                NaN
gdp_per_capita            NaN
hosp_beds                 NaN
Name: AND, dtype: object

In [15]:
covidtotals.iloc[2:4, :]

lastdate location  \
iso_code                        
DZA       2020-06-01  Algeria   
AND       2020-06-01  Andorra   

          total_cases  total_deaths  \
iso_code                              
DZA              9394           653   
AND               764            51   

          total_cases_pm  \
iso_code                   
DZA               214.22   
AND             9,888.05   

          total_deaths_pm  \
iso_code                    
DZA                 14.89   
AND                660.07   

            population  pop_density  \
iso_code                              
DZA      43,851,043.00        17.35   
AND          77,265.00       163.75   

          median_age  gdp_per_capita  \
iso_code                               
DZA            29.10       13,913.84   
AND              NaN             NaN   

          hosp_beds  
iso_code             
DZA            1.90  
AND             NaN

In [16]:
demovars_misscnt = covidtotals[demovars].isnull().sum(axis = 1)
demovars_misscnt.value_counts()

0    156
1     24
2     12
3     10
4      8
Name: count, dtype: int64

### 미션 1.
- 결측치가 3개 이상인 데이터를 추출하세요
- 추출해야 할 컬럼은 ['location'] + demovars

In [18]:
covidtotals.loc[demovars_misscnt >= 3, ['location'] + demovars]

location  \
iso_code                                    
AND                               Andorra   
AIA                              Anguilla   
BES       Bonaire Sint Eustatius and Saba   
VGB                British Virgin Islands   
FRO                        Faeroe Islands   
FLK                      Falkland Islands   
GIB                             Gibraltar   
GRL                             Greenland   
GGY                              Guernsey   
IMN                           Isle of Man   
JEY                                Jersey   
XKX                                Kosovo   
MSR                            Montserrat   
MNP              Northern Mariana Islands   
TWN                                Taiwan   
TCA              Turks and Caicos Islands   
VAT                               Vatican   
ESH                        Western Sahara   

            population  pop_density  \
iso_code                              
AND          77,265.00       163.75   
AIA          15,002.00          NaN   
BES          26,221.00          NaN   
VGB          30,237.00       207.97   
FRO          48,865.00        35.31   
FLK           3,483.00          NaN   
GIB          33,691.00     3,457.10   
GRL          56,772.00         0.14   
GGY          67,052.00          NaN   
IMN          85,032.00       147.87   
JEY         101,073.00          NaN   
XKX       1,932,774.00          NaN   
MSR           4,999.00          NaN   
MNP          57,557.00       119.88   
TWN      23,816,775.00          NaN   
TCA          38,718.00        37.31   
VAT             809.00          NaN   
ESH         597,330.00          NaN   

          median_age  gdp_per_capita  \
iso_code                               
AND              NaN             NaN   
AIA              NaN             NaN   
BES              NaN             NaN   
VGB              NaN             NaN   
FRO              NaN             NaN   
FLK              NaN             NaN   
GIB              NaN             NaN   
GRL              NaN             NaN   
GGY              NaN             NaN   
IMN              NaN             NaN   
JEY              NaN             NaN   
XKX              NaN             NaN   
MSR              NaN             NaN   
MNP              NaN             NaN   
TWN            42.20             NaN   
TCA              NaN             NaN   
VAT              NaN             NaN   
ESH            28.40             NaN   

          hosp_beds  
iso_code             
AND             NaN  
AIA             NaN  
BES             NaN  
VGB             NaN  
FRO             NaN  
FLK             NaN  
GIB             NaN  
GRL             NaN  
GGY             NaN  
IMN             NaN  
JEY             NaN  
XKX             NaN  
MSR             NaN  
MNP             NaN  
TWN             NaN  
TCA             NaN  
VAT             NaN  
ESH             NaN

## Index Alignment
- 인덱스의 값끼리 연산이 이뤄지는 것을 말함. Pandas에서 제공함

In [21]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])

#print(s1, "\n", s2)
print(s1 + s2)

a    2
b    4
c    6
d    8
dtype: int64


## 코로나 관련 변수만 추출
- 결측값이 있는지 확인
- 결측값이 있는 국가 하나 존재
- totvars 사용

In [26]:
covidtotals[totvars].isnull().sum(axis=0)
totvarsmisscnt = covidtotals[totvars].isnull().sum(axis=1)
covidtotals.loc[totvarsmisscnt>0].T

iso_code                 HKG
lastdate          2020-05-26
location           Hong Kong
total_cases                0
total_deaths               0
total_cases_pm           NaN
total_deaths_pm          NaN
population      7,496,988.00
pop_density         7,039.71
median_age             44.80
gdp_per_capita     56,054.92
hosp_beds                NaN

In [27]:
covidtotalsonly = covidtotals.loc[:, totvars]
covidtotalsonly

location  total_cases  \
iso_code                                
AFG          Afghanistan        15205   
ALB              Albania         1137   
DZA              Algeria         9394   
AND              Andorra          764   
AGO               Angola           86   
...                  ...          ...   
VNM              Vietnam          328   
ESH       Western Sahara           23   
YEM                Yemen          323   
ZMB               Zambia         1057   
ZWE             Zimbabwe          178   

          total_deaths  \
iso_code                 
AFG                257   
ALB                 33   
DZA                653   
AND                 51   
AGO                  4   
...                ...   
VNM                  0   
ESH                  1   
YEM                 80   
ZMB                  7   
ZWE                  4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   
...                  ...   
VNM                 3.37   
ESH                38.51   
YEM                10.83   
ZMB                57.50   
ZWE                11.98   

          total_deaths_pm  
iso_code                   
AFG                  6.60  
ALB                 11.47  
DZA                 14.89  
AND                660.07  
AGO                  0.12  
...                   ...  
VNM                  0.00  
ESH                  1.67  
YEM                  2.68  
ZMB                  0.38  
ZWE                  0.27  

[210 rows x 5 columns]

In [32]:
covidtotalsonly = covidtotals.loc[:, totvars]
covidtotalsonly['total_cases_q'] = pd.qcut(covidtotalsonly['total_cases'],
                                          labels=['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q = 5, precision=0)

covidtotalsonly['total_deaths_q'] = pd.qcut(covidtotalsonly['total_deaths'],
                                          labels=['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                          q = 5, precision=0)

covidtotalsonly.head(1)

location  total_cases  \
iso_code                             
AFG       Afghanistan        15205   

          total_deaths  \
iso_code                 
AFG                257   

          total_cases_pm  \
iso_code                   
AFG               390.59   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   

         total_cases_q total_deaths_q  
iso_code                               
AFG                 높음             높음

In [33]:
pd.crosstab(covidtotalsonly['total_cases_q'], covidtotalsonly['total_deaths_q'])

total_deaths_q  매우낮음  낮음  중간  높음  매우높음
total_cases_q                         
매우낮음              34   7   1   0     0
낮음                12  19  10   1     0
중간                 1  13  15  13     0
높음                 0   0  12  24     6
매우높음               0   0   2   4    36

In [35]:
covidtotals.loc[(covidtotalsonly.total_case_q=="매우높음") * (covidtotalsonly.total_case_q=="중간")].T

AttributeError: 'DataFrame' object has no attribute 'total_case_q'